env:
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  semi: off,
  eqeqeq: error,
  no-trailing-spaces: error,
  no-console: off
}
